version: '3.5'

services:
  frontend-prod:
    container_name: frontend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      NODE_PATH: /usr/src/frontend/src
      REACT_APP_ENV: production
      HTTPS: "true"
    env_file:
      - ./common.env
    depends_on:
      - api-prod
  
  api-prod:
    build:
      context: .
      dockerfile: Dockerfile.node
      args:
        PACKAGE_PATH: ./api
        WORKING_DIR: /usr/src/api
    expose:
      - 8000
    ports:
      - 8000:8000
    env_file:
      - ./common.env
    volumes:
      - .:/src
    depends_on:
      - postgres
    command: ["npm", "start"]

  postgres:
    image: postgres
    restart: always
    env_file:
      ./common.env